BlijvenLeren/Controllers/CommentsController.cs
using BlijvenLeren.Repository;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BlijvenLeren.Controllers
{
    public class CommentsController : Controller
    {
        IBlijvenLerenRepository _repo;

        public CommentsController(IBlijvenLerenRepository repo)
        {
            _repo = repo;
        }

        public ActionResult Index()
        {
            return View(_repo.GetCommentsForReview());
        }

        // GET: CommentsController/Edit/5
        public ActionResult Edit(int id)
        {
            _repo.ApproveComment(id);
            return RedirectToAction("Index");
        }

        // POST: CommentsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: CommentsController/Delete/5
        public ActionResult Delete(int id)
        {
            _repo.DeleteComment(id);
            return RedirectToAction("Index");
        }

        // POST: CommentsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

BlijvenLeren/Controllers/LearnResourcesController.cs
using BlijvenLeren.Models;
using BlijvenLeren.Repository;
using BlijvenLeren.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace BlijvenLeren.Controllers
{
    [Authorize]
    public class LearnResourcesController : Controller
    {
        private readonly IBlijvenLerenRepository _repo;
        private readonly IUserService _userService;

        public LearnResourcesController(IBlijvenLerenRepository repo, IUserService userService)
        {
            _repo = repo;
            _userService = userService;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _repo.GetAllLearnResources());
        }

        [HttpGet]
        [Route("api/learnresource/{id}")]
        public LearnResource Get(int id)
        {
            return _repo.GetLearnResourceDetails((int)id).Result.LearnResource;
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            LearnResourcesViewModel vm = _repo.GetLearnResourceDetails((int)id).Result;

            if (vm.LearnResource == null)
            {
                return NotFound();
            }
            
            return View(vm);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("LearnResourceId,Title,Description,Link")] LearnResource learnResource)
        {
            if (ModelState.IsValid)
            {
                await _repo.AddLearnResource(learnResource);

                return RedirectToAction(nameof(Index));
            }
            return View(learnResource);
        }

        public IActionResult NewComment(int id)
        {
            return View(new Comment() { LearnResourceId = id, Status = BepaalStatusOpBasisVanUserRol() });
        }

        private CommentStatus BepaalStatusOpBasisVanUserRol()
        {
            var status = User.IsInRole(BlijvenLerenRole.Intern) ? CommentStatus.Approved : CommentStatus.InReview;

            return status;
        }

        public async Task<IActionResult> AddComment([Bind("LearnResourceId, Status, CommentText")] Comment newComment)
        {
            await _repo.AddComment(newComment);

            return RedirectToAction("Details", new { id = newComment.LearnResourceId });
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var learnResource = await _repo.GetLearnResource((int)id);
            if (learnResource == null)
            {
                return NotFound();
            }
            return View(learnResource);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("LearnResourceId,Title,Description,Link")] LearnResource learnResource)
        {
            if (id != learnResource.LearnResourceId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _repo.UpdateLearnResource(learnResource);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_repo.LearnResourceExists(learnResource.LearnResourceId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(learnResource);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var learnResource = await _repo.GetLearnResource((int)id);

            if (learnResource == null)
            {
                return NotFound();
            }

            return View(learnResource);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _repo.DeleteLearnResource(id);

            return RedirectToAction(nameof(Index));
        }
    }
}

BlijvenLeren/Views/Shared/_Layout.cshtml
@inject BlijvenLeren.Repository.IBlijvenLerenRepository repo; 

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BlijvenLeren</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BlijvenLeren</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <div class=" navbar-nav" style="color: rgb(176 176 176)">Logged in as @User.Identity.Name</div>
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="LearnResources" asp-action="Index">Learn</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            @if (User.IsInRole(BlijvenLerenRole.Intern) && repo.GetCommentsForReview().Count() > 0)
                            {
                            <li class="nav-item">
                                <a class="nav-link text-danger" asp-area="" asp-controller="Comments" asp-action="Index">Review</a>
                            </li>
                            }
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                            </li>
                        </ul>
                    }
                    else
                    {
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                            </li>
                        </ul>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - BlijvenLeren - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>